### ISSUE TITLE
Suggestion: Implement method for adding messages without config reload

### ISSUE THREAD

**Issue by Z8MB1E** [HHServers/BBroadcast#1]
Hey there, I have a suggestion! Would it be possible to implement some way of adding new messages to the announcer without having to modify the config itself? For example, a command like `/bb add message:String title:Boolean world:String random:Boolean` that allows you to add a message from chat? If this is possible, could a remove command also be added?

Examples:

- `/bb add "Hello world!" false world true`
- `/bb remove "Hello world!"` or using indexes instead:
- `/bb remove 1`

I definitely believe this would be a great addition to this plugin!

**Comment by HHServers** [comment]
Thank you for the suggestion! This is definitely within my knowledge to do. Expect an update soon :)

**Comment by Z8MB1E** [comment]
> Thank you for the suggestion! This is definitely within my knowledge to do. Expect an update soon :)

Outstanding, I look forward to the update! 👍

**Comment by HHServers** [comment]
I just noticed I didn't add a remove command LMAO. I'm sorry - i'll do this tonight

**Comment by HHServers** [comment]
V1.21 on ORE now can add and remove broadcasts. 
/bb add “message” Title?:true/false “worldname” Random?:true/false Interval: X
/bb list random/timed (can remove in this menu)
